import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`bg-gray-200`}>
        <div className={'mt-10'}></div>
        {children}
      </body>
    </html>
  );
}

export function NavigationBar(){
    return(
        <>
            <div className={`flex-shrink h-8 w-auto flex-row mb-6 items-center justify-center content-center`}>
                <Logo></Logo>
                <NavButton>About us</NavButton>
            </div>
            <hr/>
        </>

    );
}
export function NavButton({children}: Readonly<{ children: React.ReactNode; }>){
    return(
        <div className={`inline-flex rounded-md transition-all duration-150 hover:bg-green-400 text-xl`}>&nbsp;{children}&nbsp;</div>
    );
}
export function Logo(){
    return(
        <div className={`inline-flex rounded-md transition-all duration-150 hover:bg-green-400 text-xl logo-comfortaa flex-row justify-evenly items-center`}>
            <img src="/logo.png" alt="" className={`w-9 h-9`}/><p>Entangled</p>
        </div>
    );
}

export function FadeInCard({children}: Readonly<{ children: React.ReactNode; }>){
    return(
        <div className={`bg`}>&nbsp;{children}&nbsp;</div>
    );
}

